### ISSUE TITLE
Error when calling image_generator_real from Image_generation_examples notebook

### ISSUE THREAD

**Issue by sidwan02** [BastienArcelin/image_generation_GalSim#1]
# Issue Brief

This issue concerns `Image_generation_examples.ipynb`, for the code under the header `Generate image of isolated galaxies`.

Running the cell that calls `image_generator_real` leads to an error in `images_generator.py` at:
```
psf_image = PSF[6].drawImage(nx=max_stamp_size, ny=max_stamp_size, scale=pixel_scale[6])
```
which is:
```
AttributeError: 'tuple' object has no attribute 'drawImage'
```

# Attempted Debugging
I have tried debugging by printing `PSF`:
<img width="577" alt="image" src="https://user-images.githubusercontent.com/70694457/151047118-3a6c216c-907a-41e9-82a4-9cd29638302e.png">
and by printing the type of each element in `PSF`:
<img width="190" alt="image" src="https://user-images.githubusercontent.com/70694457/151049248-6a197145-5a90-448e-a337-764ada49bb81.png">
where indeed we see that `PSF[6]` is a tuple.

# Attempted Resolution

I naively tried to resolve this by extracting the first element of every tuple by inserting the following line in `images_generator.py` before `PSF[6].drawImage`:
```
PSF = list(map(lambda x: x[0] if type(x) == tuple else x, PSF))
```
but it results in a different error:
```
TypeError: not all arguments converted during string formatting
```
at this part of `images_generator.py`:
```
# Draw real images
--> galaxies_real_psf = [galsim.Convolve([real_gal*coeff_exp[6], PSF_lsst]) for real_gal in real_gal_list]
```

# Additional Details

I am running the notebook from a Conda environment running in WSL.

PS: running the cells of the notebook that call `image_generator_sim` work fine.

**Comment by BastienArcelin** [comment]
I @sidwan02. Thanks for the issue. I found the bug, it was a problem with the call of the function `psf_lsst` at the start of the `image_generator_real` function. Commit [cbe5e47](https://github.com/BastienArcelin/image_generation_GalSim/commit/cbe5e477811cda8f60d9c18ca73c57b72255c35b) corrected for it. It should work fine now so I close the issue. Tell me if otherwise so I will reopen it
